name: every sunday and tuesday

on:
  schedule:
    # ุงูุฃุญุฏ (0) ูุงูุซูุงุซุงุก (2) ุงูุณุงุนุฉ 2:00 ุตุจุงุญุงู ุจุชูููุช ูุตุฑ
    # ุชุนุงุฏู 00:00 ุจุชูููุช ุฌุฑููุชุด
    - cron: '0 0 * * 0,2'
  workflow_dispatch: # ูุชูุญ ูู ุชุฌุฑุจุฉ ุงูุฅุฑุณุงู ุงูุขู ูุฏููุงู

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        run: |
          # ุถุจุท ุชูููุช ูุตุฑ
          export TZ='Africa/Cairo'
          CUR_DATE=$(date +'%Y-%m-%d')
          CUR_TIME=$(date +'%H:%M:%S')
          
          # ุฅุนุฏุงุฏุงุช ุจูุช ุดูุณ
          TOKEN="8305317876:AAHkPFr8idftz1Rgc6-tdCugaaZTrQsZnP4"
          CHAT_ID="-5216371452"
          
          # ูุต ุงูุฑุณุงูุฉ ุงููุนุฏู
          MESSAGE="๐ *ููุงุนูุฏ ุงูููุฑุณ*%0A%0Aููู ุงูุฑ ุงูุทุงูุจ ุงุญูุฏ ูุญูุฏ ููุณู%0A*ุงูููุถูุน:* ุชุฐููุฑ ุจููุนุงุฏ ุงูููุฑุณ ูููู ุงูุงุญุฏ ูุงูุซูุงุซุงุก ุงูุณุงุนู ุงูุซุงููู ุตุจุงุญุงู%0A%0A๐ *ุงูุชุงุฑูุฎ:* $CUR_DATE%0Aโฐ *ุงูููุช:* $CUR_TIME"
          
          # ุชูููุฐ ุนูููุฉ ุงูุฅุฑุณุงู
          curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
          -d "chat_id=$CHAT_ID" \
          -d "text=$MESSAGE" \
          -d "parse_mode=Markdown"
